[tool.poetry]
name = "levantamento-patrimonial"
version = "0.1.0"
description = ""
authors = ["Mateus Pinheiro <mateus.mcpa@gmail.com>"]
readme = "README.md"

package-mode = false

[tool.poetry.dependencies]
python = ">=3.10,<3.11"
fastapi = "^0.111.0"
uvicorn = "^0.30.1"
streamlit = "^1.49.1"
python-dotenv = "^1.1.1"
psycopg2-binary = "^2.9.10"
pandas = "^2.3.2"
python-multipart = "^0.0.20"
tqdm = "^4.67.1"
python-calamine = "^0.5.3"
openpyxl = "^3.1.5"
pydantic = "2.11.7"
st-pages = "^1.0.1"
matplotlib = "^3.10.6"
seaborn = "^0.13.2"


[tool.poetry.group.dev.dependencies]
honcho = "^2.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
